#!/usr/bin/env python3
"""Route a user question to FengShui Master references."""

from __future__ import annotations

import argparse
import json


def score_question(question: str, keywords: set[str]) -> int:
    normalized = question.lower()
    words = {token.strip(".,?!:;()[]{}\"'").lower() for token in question.split()}
    score = len(words & keywords)

    for keyword in keywords:
        if keyword and keyword in normalized and keyword not in words:
            score += 1

    return score


DOMAIN_RULES = [
    (
        "timing",
        {
            "moon",
            "lunar",
            "solar",
            "term",
            "terms",
            "season",
            "seasonal",
            "jieqi",
            "lichun",
            "equinox",
            "solstice",
            "newmoon",
            "fullmoon",
            "new",
            "full",
            "launch",
            "move",
            "moving",
            "opening",
            "renovation",
            "月相",
            "新月",
            "满月",
            "节气",
            "二十四节气",
            "立春",
            "春分",
            "夏至",
            "秋分",
            "冬至",
            "朔",
            "望",
            "朔望",
            "择日",
            "择时",
            "日期",
            "开业",
            "搬家",
            "装修",
            "动土",
        },
        [
            "references/timing-and-date-selection.md",
            "references/broad-symbolic-analysis.md",
            "references/ethics-and-limits.md",
        ],
        [
            "moon phase and solar terms are secondary symbolic timing layers, not a full almanac or guaranteed auspiciousness method.",
            "Do not guarantee outcomes from new moon, full moon, lunar phase, solar term, seasonal qi, or any single timing marker.",
            "Use event type, candidate dates, local time zone, practical constraints, and lineage-specific calendar attributes before symbolic timing.",
        ],
    ),
    (
        "life_omen",
        {
            "auspicious",
            "inauspicious",
            "omen",
            "omens",
            "luck",
            "lucky",
            "unlucky",
            "fortune",
            "destiny",
            "fate",
            "life",
            "lifepath",
            "biography",
            "person",
            "personal",
            "bazi",
            "birth",
            "year",
            "凶",
            "吉凶",
            "不吉",
            "运势",
            "运气",
            "命",
            "命运",
            "命理",
            "生平",
            "人生",
            "个人",
            "财运",
            "趋吉避凶",
            "八字",
            "出生",
        },
        [
            "references/broad-symbolic-analysis.md",
            "references/life-and-omen-adapter.md",
            "references/five-phase-domain-map.md",
            "references/foundation.md",
            "references/ethics-and-limits.md",
        ],
        [
            "Do not make deterministic fate, health, death, wealth, marriage, or disaster claims.",
            "Use feng shui, yin-yang, wuxing, bagua, and timing as symbolic analysis, not guaranteed prediction.",
            "Disclose when full bazi, zi wei, qimen, liuren, or almanac calculation is not implemented.",
        ],
    ),
    (
        "finance",
        {
            "stock",
            "stocks",
            "bond",
            "portfolio",
            "investment",
            "invest",
            "trading",
            "crypto",
            "bitcoin",
            "fund",
            "financial",
            "finance",
            "market",
            "risk",
            "cash",
            "budget",
            "wealth",
            "股票",
            "投资",
            "理财",
            "基金",
            "债券",
            "加密",
            "比特币",
            "市场",
            "财运",
            "财富",
            "现金",
            "预算",
            "风险",
        },
        [
            "references/broad-symbolic-analysis.md",
            "references/finance-adapter.md",
            "references/domain-adapters.md",
            "references/five-phase-domain-map.md",
            "references/ethics-and-limits.md",
            "references/timing-and-date-selection.md",
        ],
        [
            "This is not financial advice.",
            "Do not guarantee profit, timing, or risk-free outcomes.",
            "Use feng shui as a symbolic decision-support lens alongside real financial analysis.",
        ],
    ),
    (
        "product",
        {
            "product",
            "onboarding",
            "ux",
            "user",
            "users",
            "feature",
            "features",
            "roadmap",
            "activation",
            "retention",
            "conversion",
            "funnel",
            "app",
            "software",
            "产品",
            "用户",
            "体验",
            "功能",
            "路线图",
            "激活",
            "留存",
            "转化",
            "漏斗",
            "应用",
            "软件",
        },
        [
            "references/broad-symbolic-analysis.md",
            "references/product-adapter.md",
            "references/domain-adapters.md",
            "references/five-phase-domain-map.md",
            "references/ethics-and-limits.md",
        ],
        [
            "Do not replace user research, accessibility, security, privacy, analytics, or engineering review.",
            "Use feng shui as a metaphor for user flow, support, friction, and leakage.",
        ],
    ),
    (
        "brand",
        {
            "brand",
            "branding",
            "logo",
            "color",
            "colors",
            "launch",
            "naming",
            "marketing",
            "campaign",
            "品牌",
            "标志",
            "颜色",
            "命名",
            "营销",
            "发布",
        },
        [
            "references/broad-symbolic-analysis.md",
            "references/brand-adapter.md",
            "references/domain-adapters.md",
            "references/five-phase-domain-map.md",
            "references/foundation.md",
            "references/remedies.md",
            "references/ethics-and-limits.md",
        ],
        [
            "Do not replace market research, accessibility, or legal trademark review.",
            "Use five phases and yin-yang as symbolic design constraints.",
        ],
    ),
    (
        "business",
        {
            "business",
            "strategy",
            "operations",
            "revenue",
            "customers",
            "customer",
            "sales",
            "startup",
            "company",
            "partnership",
            "fundraising",
            "hiring",
            "商业",
            "生意",
            "业务",
            "战略",
            "运营",
            "收入",
            "客户",
            "销售",
            "创业",
            "公司",
            "合伙",
            "融资",
            "招聘",
        },
        [
            "references/broad-symbolic-analysis.md",
            "references/business-adapter.md",
            "references/domain-adapters.md",
            "references/five-phase-domain-map.md",
            "references/ethics-and-limits.md",
        ],
        [
            "Do not guarantee revenue, growth, funding, or market outcomes.",
            "Use business fundamentals first: customers, margins, cash flow, team, and constraints.",
        ],
    ),
    (
        "career",
        {
            "career",
            "job",
            "promotion",
            "interview",
            "negotiation",
            "team",
            "leadership",
            "boss",
            "work",
            "职业",
            "事业",
            "工作",
            "升职",
            "面试",
            "谈判",
            "领导",
            "团队",
        },
        [
            "references/broad-symbolic-analysis.md",
            "references/career-adapter.md",
            "references/domain-adapters.md",
            "references/life-and-omen-adapter.md",
            "references/five-phase-domain-map.md",
            "references/analysis-templates.md",
            "references/ethics-and-limits.md",
        ],
        [
            "Do not promise career outcomes.",
            "Combine symbolic timing and environment advice with practical preparation.",
        ],
    ),
    (
        "relationship",
        {
            "relationship",
            "relationships",
            "romance",
            "romantic",
            "marriage",
            "partner",
            "family",
            "friendship",
            "conflict",
            "communication",
            "roommate",
            "关系",
            "感情",
            "恋爱",
            "婚姻",
            "伴侣",
            "家庭",
            "家人",
            "朋友",
            "冲突",
            "沟通",
            "室友",
        },
        [
            "references/broad-symbolic-analysis.md",
            "references/relationship-adapter.md",
            "references/domain-adapters.md",
            "references/five-phase-domain-map.md",
            "references/ethics-and-limits.md",
        ],
        [
            "Do not predict marriage, divorce, pregnancy, affairs, reconciliation, or another person's feelings.",
            "Prioritize consent, communication, privacy, and safety.",
        ],
    ),
    (
        "learning",
        {
            "learning",
            "study",
            "studying",
            "exam",
            "exams",
            "memory",
            "practice",
            "focus",
            "course",
            "school",
            "education",
            "certification",
            "学习",
            "读书",
            "考试",
            "记忆",
            "练习",
            "专注",
            "课程",
            "学校",
            "教育",
            "证书",
        },
        [
            "references/broad-symbolic-analysis.md",
            "references/learning-adapter.md",
            "references/domain-adapters.md",
            "references/five-phase-domain-map.md",
            "references/ethics-and-limits.md",
        ],
        [
            "Do not guarantee exam success, admission, memory, or mastery.",
            "Use feng shui as an environment, rhythm, attention, and review-cycle support lens.",
        ],
    ),
    (
        "legal_adjacent",
        {
            "legal",
            "law",
            "contract",
            "contracts",
            "dispute",
            "court",
            "lawsuit",
            "compliance",
            "lease",
            "inheritance",
            "filing",
            "clause",
            "clauses",
            "法律",
            "合同",
            "契约",
            "纠纷",
            "争议",
            "法院",
            "诉讼",
            "合规",
            "租约",
            "继承",
            "条款",
        },
        [
            "references/broad-symbolic-analysis.md",
            "references/legal-adjacent-adapter.md",
            "references/domain-adapters.md",
            "references/five-phase-domain-map.md",
            "references/ethics-and-limits.md",
        ],
        [
            "Do not provide legal advice.",
            "Legal rights, obligations, deadlines, evidence, jurisdiction, and counsel take priority.",
        ],
    ),
    (
        "wellbeing",
        {
            "health",
            "sleep",
            "stress",
            "wellbeing",
            "wellness",
            "anxiety",
            "focus",
            "energy",
            "健康",
            "睡眠",
            "压力",
            "焦虑",
            "专注",
            "精力",
        },
        [
            "references/broad-symbolic-analysis.md",
            "references/wellbeing-adapter.md",
            "references/domain-adapters.md",
            "references/life-and-omen-adapter.md",
            "references/analysis-templates.md",
            "references/ethics-and-limits.md",
        ],
        [
            "Do not diagnose or treat medical conditions.",
            "Prioritize light, air, sleep, ergonomics, and professional care where needed.",
        ],
    ),
    (
        "space",
        {
            "home",
            "house",
            "apartment",
            "bedroom",
            "office",
            "desk",
            "kitchen",
            "bathroom",
            "mirror",
            "door",
            "floor",
            "layout",
            "room",
            "shop",
            "store",
            "land",
            "site",
            "住宅",
            "房子",
            "公寓",
            "卧室",
            "办公室",
            "书桌",
            "厨房",
            "卫生间",
            "镜子",
            "门",
            "户型",
            "布局",
            "商铺",
            "店铺",
            "土地",
            "墓地",
        },
        [
            "references/analysis-templates.md",
            "references/forms-and-environment.md",
            "references/remedies.md",
            "references/ethics-and-limits.md",
        ],
        [
            "Use observable form and safety before symbolic judgments.",
        ],
    ),
]


def route(question: str) -> dict[str, object]:
    best = None
    best_score = 0
    for domain, keywords, references, guardrails in DOMAIN_RULES:
        score = score_question(question, keywords)
        if score > best_score:
            best = (domain, references, guardrails)
            best_score = score

    if best is None:
        best = (
            "general",
            [
                "references/broad-symbolic-analysis.md",
                "references/domain-adapters.md",
                "references/foundation.md",
                "references/ethics-and-limits.md",
            ],
            [
                "Identify the domain first, then apply feng shui as an auxiliary symbolic lens.",
            ],
        )

    domain, references, guardrails = best
    return {
        "domain": domain,
        "references": references,
        "guardrails": guardrails,
        "lens": [
            "yin-yang balance",
            "five-phase relationships",
            "timing and activation",
            "form, flow, and containment",
            "risk and remedy hierarchy",
        ],
    }


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Route a cross-domain question to FengShui Master references."
    )
    parser.add_argument("question", help="User question or short task description.")
    parser.add_argument("--pretty", action="store_true", help="Print indented JSON.")
    args = parser.parse_args()

    print(json.dumps(route(args.question), ensure_ascii=True, indent=2 if args.pretty else None))


if __name__ == "__main__":
    main()
